'use strict';import{AssertionError,AttributeError,BaseException,DeprecationWarning,Exception,IndexError,IterableError,KeyError,NotImplementedError,RuntimeWarning,StopIteration,UserWarning,ValueError,Warning,__JsIterator__,__PyIterator__,__Terminal__,__add__,__and__,__call__,__class__,__envir__,__eq__,__floordiv__,__ge__,__get__,__getcm__,__getitem__,__getslice__,__getsm__,__gt__,__i__,__iadd__,__iand__,__idiv__,__ijsmod__,__ilshift__,__imatmul__,__imod__,__imul__,__in__,__init__,__ior__,__ipow__,
__irshift__,__isub__,__ixor__,__jsUsePyNext__,__jsmod__,__k__,__kwargtrans__,__le__,__lshift__,__lt__,__matmul__,__mergefields__,__mergekwargtrans__,__mod__,__mul__,__ne__,__neg__,__nest__,__or__,__pow__,__pragma__,__proxy__,__pyUseJsNext__,__rshift__,__setitem__,__setproperty__,__setslice__,__sort__,__specialattrib__,__sub__,__super__,__t__,__terminal__,__truediv__,__withblock__,__xor__,abs,all,any,assert,bool,bytearray,bytes,callable,chr,copy,deepcopy,delattr,dict,dir,divmod,enumerate,filter,float,
getattr,hasattr,input,int,isinstance,issubclass,len,list,map,max,min,object,ord,pow,print,property,py_TypeError,py_iter,py_metatype,py_next,py_reversed,py_typeof,range,repr,round,set,setattr,sorted,str,sum,tuple,zip}from"./org.transcrypt.__runtime__.js";import{time}from"./time.js";var __name__="mysearch";export var search=function(password,matches){var output=[];var used_entries=[];var bruteforce_strings=[];var brute=[];var brute_positions=[];var password_buffer=list(password);for(var match of matches)if(!__in__(match["i"]||
match["j"],used_entries)){output.append(match);for(var x=match["i"];x<match["j"]+1;x++){password_buffer[x]="OUT";used_entries.append(x)}}for(var [position,value]of enumerate(password_buffer)){if(value!=="OUT"){brute.extend(value);brute_positions.append(position)}if(value==="OUT"&&brute||position==len(password_buffer)-1&&brute){var bf_word="".join(brute);output.append(dict({"pattern":"bruteforce","i":brute_positions[0],"j":brute_positions[-1],"token":bf_word,"matched_length":len(bf_word)}));var brute=
[];var brute_positions=[]}}return sorted(output,__kwargtrans__({key:function __lambda__(x){return tuple([x["i"],x["j"]])}}))};if(__name__=="__main__"){var start=time();var password="tyqewxt3stingzfhHelpwtg";var matches=[dict({"pattern":"dictionary","i":6,"j":12,"token":"t3sting","matched_word":"testing","matched_length":7,"rank":398,"dictionary_name":"passwords","l33t":true,"sub":dict({3:"e"}),"sub_display":"3 -> e"}),dict({"pattern":"dictionary","i":6,"j":11,"token":"t3stin","matched_word":"testin",
"matched_length":6,"rank":22215,"dictionary_name":"passwords","l33t":true,"sub":dict({3:"e"}),"sub_display":"3 -> e"}),dict({"pattern":"dictionary","i":8,"j":12,"token":"sting","matched_word":"sting","matched_length":5,"rank":2801,"dictionary_name":"passwords","l33t":false}),dict({"pattern":"dictionary","i":9,"j":12,"token":"ting","matched_word":"ting","matched_length":4,"rank":3313,"dictionary_name":"passwords","l33t":false}),dict({"pattern":"dictionary","i":16,"j":19,"token":"Help","matched_word":"help",
"matched_length":4,"rank":103,"dictionary_name":"us_tv_and_film","l33t":false}),dict({"pattern":"dictionary","i":6,"j":9,"token":"t3st","matched_word":"test","matched_length":4,"rank":93,"dictionary_name":"passwords","l33t":true,"sub":dict({3:"e"}),"sub_display":"3 -> e"}),dict({"pattern":"dictionary","i":10,"j":11,"token":"in","matched_word":"in","matched_length":2,"rank":4,"dictionary_name":"english_wikipedia","l33t":false}),dict({"pattern":"dictionary","i":16,"j":17,"token":"He","matched_word":"he",
"matched_length":2,"rank":12,"dictionary_name":"english_wikipedia","l33t":false}),dict({"pattern":"dictionary","i":10,"j":10,"token":"i","matched_word":"i","matched_length":1,"rank":2,"dictionary_name":"us_tv_and_film","l33t":false})];print(search(password,matches));var end=time();print(end-start,"seconds")};

//# sourceMappingURL=mysearch.map